version: '3.4'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes: 
            - ./mongo-data:/data/db
    todo-api:
        build: 
            context: ./api            
        ports: 
            - "9000:9000"
        environment: 
            - "MONGO_DB=mongo"

        depends_on:
            - mongo
    todo-client:
        build:
            context: ./client
        ports: 
            - "3000:80"
        depends_on:
            - todo-api